"""add rating to recipe_categories

Revision ID: 46b66c13ca11
Revises: 1b869bf8affa
Create Date: 2025-10-16 09:17:53.069251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b66c13ca11'
down_revision = '1b869bf8affa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_categories', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
